source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'LPThirdPlatformKit_Example' do
  pod 'LPThirdPlatformKit', :path => '../'

  target 'LPThirdPlatformKit_Tests' do
    inherit! :search_paths

    
  end
end
